
#如果要使用Druid连接池的话，就把pom中的Druid依赖包放开，springboot会自动检查到有第三方连接池，就会使用Druid连接池，
# 否则 如果不自己加入连接池依赖，springboot就使用默认的号称史上最快的连接池Hikari。
# (注意：要确保mysql数据库服务的配置与连接池配置匹配，例如最大连接数等，以避免连接池配置超出数据库的限制。)
#初始化连接数量。
spring.datasource.druid.initial-size=5  
#最小空闲连接数(与数据库持续保持连接的数量)，少于则创建。要与数据库的连接数配置批量，如果数据库服务本身配置了最大连接数只有150，而这里配置的
# 最小空闲连接数就有150左右的话，那会一直占有数据库的全部连接资源，导致其他服务无法连接数据库。
spring.datasource.druid.min-idle=5
#最大空闲连接数，超过则回收。
spring.datasource.druid.max-active=20
#获取连接时最大等待时间，单位毫秒。
spring.datasource.druid.max-wait=6000
#是否缓存PreparedStatement。
spring.datasource.druid.pool-prepared-statements=true
#spring.datasource.druid.max-open-prepared-statements=
spring.datasource.druid.max-pool-prepared-statement-per-connection-size=20
spring.datasource.druid.validation-query-timeout=6000
#获取连接时是否验证连接。
spring.datasource.druid.test-on-borrow=false
#释放连接时是否验证连接。
spring.datasource.druid.test-on-return=false
#是否在空闲时验证连接。
spring.datasource.druid.test-while-idle=true
#验证空闲连接是否有效的时间间隔。
spring.datasource.druid.time-between-eviction-runs-millis=60000
#空闲连接有效时间，超时则被回收。
spring.datasource.druid.min-evictable-idle-time-millis=25200000
#用于验证连接是否有效的SQL。
spring.datasource.druid.validation-query=SELECT 1
#spring.datasource.druid.max-evictable-idle-time-millis=
#是否自动回收超时连接。
spring.datasource.druid.removeAbandoned=true
#超时时间。
spring.datasource.druid.remove-abandoned-timeout=1800
#是否记录回收的日志。
spring.datasource.druid.log-abandoned=true
#配置监控统计拦截的filters
spring.datasource.druid.filters=stat,wall,log4j

# 配置StatViewServlet（下面的几个配置是开启监控页面的）
#开启监控页面（是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全））
spring.datasource.druid.stat-view-servlet.enabled=true
#监控页面的地址（访问的时候别忘了前面还有项目的根路径地址）
spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
#登录的账户和密码
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=admin
#IP 白名单，没有配置或者为空，则允许所有访问
spring.datasource.druid.stat-view-servlet.allow=127.0.0.1
#IP 黑名单，若白名单也存在，则优先使用
spring.datasource.druid.stat-view-servlet.deny=192.168.31.253
#是否开启监控页面上的“重置”按钮，点击这个按钮会清空所有已经统计的sql监控数据，默认开启
spring.datasource.druid.stat-view-servlet.reset-enable=false
# 配置DruidWebStatFilter
spring.datasource.druid.web-stat-filter.enabled=true
spring.datasource.druid.web-stat-filter.url-pattern=/*
spring.datasource.druid.web-stat-filter.exclusions=*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
#启用会话统计功能
spring.datasource.druid.web-stat-filter.session-stat-enable=true
#最大会话统计数量
spring.datasource.druid.web-stat-filter.session-stat-max-count=1000

# SQL监控配置
#开启DruidDataSource状态监控
spring.datasource.druid.filter.stat.enabled=true
# 数据库的类型
spring.datasource.druid.filter.stat.db-type=mysql
# 开启慢SQL记录功能
spring.datasource.druid.filter.stat.log-slow-sql=true
# 默认3000毫秒就是慢sql，这里自己酌情配置，慢sql会记录到日志
spring.datasource.druid.filter.stat.slow-sql-millis=100
# 防火墙配置
spring.datasource.druid.filter.wall.config.multi-statement-allow=true
# Keep-Alive配置
spring.datasource.druid.keep-alive=true
#spring 监控(访问druid页面之后”spring监控“里默认是没有数据的，这里配置spring监控AOP切入点，多个英文逗号分隔，但需要导入SprngBoot的AOP的Starter（spring-boot-starter-aop）)
spring.datasource.druid.aop-patterns="com.security.order.*"





## HikariCP 连接池配置(注意：要确保mysql数据库服务的配置与连接池配置匹配，例如最大连接数等，以避免连接池配置超出数据库的限制。)
##连接池中最小空闲连接数。当连接数少于该值时，连接池会尝试补充新的连接。
#spring.datasource.hikari.minimum-idle=5
##连接池中最大连接数。这是连接池可以分配的最大连接数。
#spring.datasource.hikari.maximum-pool-size=20
##连接在池中闲置的最长时间（毫秒），超过这个时间，连接将被释放。
#spring.datasource.hikari.idle-timeout=30000
##连接池中连接的最长存活时间（毫秒）。连接超过这个时间将被释放并重新建立。
#spring.datasource.hikari.max-lifetime=1800000
##连接池在获取连接时的超时时间（毫秒）,超过这个时间将抛出 SQLTimeoutException。
#spring.datasource.hikari.connection-timeout=30000
##连接池的名称。
#spring.datasource.hikari.pool-name=MyHikariCP
##连接泄漏检测的阈值（毫秒）。如果连接超过这个时间未被归还，则会记录日志。适用于调试和诊断连接泄漏。
#spring.datasource.hikari.leak-detection-threshold=2000