image: openjdk:8-jdk

stages:
  - build
  - test
  - docker_build
  - deploy

variables:
  DOCKER_IMAGE: security-system-1.0.0
  REGISTRY: your-docker-registry-url
  DOCKER_USERNAME: your-username
  DOCKER_PASSWORD: your-password

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

docker_build:
  stage: docker_build
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $REGISTRY
    - docker tag $DOCKER_IMAGE $REGISTRY/$DOCKER_IMAGE:latest
    - docker push $REGISTRY/$DOCKER_IMAGE:latest

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl rollout status deployment/my-java-app
