# 可以在启动的时候通过参数指定环境： java -jar myapp.jar --spring.profiles.active=tengxunyun
# 也可以通过系统环境变量指定
# 或 通过jvm参数激活：java -jar -Dspring.profiles.active=tengxunyun myapp.jar
# 等方式指定环境参数
spring.profiles.active=tengxunyun
