spring.application.name=security-market
#端口配置
server.port=8084


# 数据源配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://124.222.246.77:3306/security_market?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123987456Mdl

# nacos配置
spring.cloud.nacos.discovery.server-addr=124.222.246.77:8848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos
#利用命名空间可以实现多测试环境的服务注册隔离,也就是说：不在同一个命名空间的服务是调不通的（专栏里头有讲，自己可以测试一下）
spring.cloud.nacos.discovery.namespace=a9b8e131-eedd-40f8-9bdf-5f778779a271

#redis配置
spring.redis.host=124.222.246.77
spring.redis.port=6379
spring.redis.password=123987456Mdl
spring.redis.timeout=3000

#dubbo配置
#这个名字什么用和上面的spring.application.name一样吗
dubbo.application.name=security-market-dubbo
dubbo.scan.base-packages=com.security.market
dubbo.registry.address=nacos://124.222.246.77:8848
dubbo.registry.parameters.namespace=a9b8e131-eedd-40f8-9bdf-5f778779a271
dubbo.cloud.subscribed-services=security-order
#Dubbo协议和端口
dubbo.protocol.name=dubbo
dubbo.protocol.port=28088
dubbo.consumer.check=false
dubbo.provider.threads=800
dubbo.provider.actives=200

#mybatis配置
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.mapper-locations=classpath*:com/security/**/*.xml

#rocketmq配置
rocketmq.name-server=124.222.246.77:9876

#seata配置
# 如果引入的是seata-spring-boot-starter 请关闭自动代理，需要关闭自动代理
#seata.enable-auto-data-source-proxy=false
# Seata应用的名称
#seata.application-id=seata-server
# 事务组
seata.tx-service-group=default_tx_group
seata.service.vgroup-mapping.default_tx_group=default
#seata.config.type=nacos
# Nacos服务地址
#seata.config.nacos.server-addr=124.222.246.77:8848
#seata.config.nacos.namespace=a9b8e131-eedd-40f8-9bdf-5f778779a271
#seata.config.nacos.group=DEFAULT_GROUP
#seata.config.nacos.username=nacos
#seata.config.nacos.password=nacos
seata.registry.type=nacos
seata.registry.nacos.server-addr=124.222.246.77:8848
seata.registry.nacos.namespace=a9b8e131-eedd-40f8-9bdf-5f778779a271
seata.registry.nacos.group=DEFAULT_GROUP
seata.registry.nacos.username=nacos
seata.registry.nacos.password=nacos
#seata.registry.nacos.cluster=default
seata.registry.nacos.application=seata-server