version: '1.0'
name: pipeline-20240912
displayName: pipeline-master
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-maven-goujian
    displayName: maven构建
    strategy: naturally
    trigger: auto
    executor:
      - madongliang
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '8'
        mavenVersion: 3.3.9
        commands:
          - '# 功能：打包'
          - '# 参数说明：'
          - '#    -Dmaven.test.skip=true：跳过单元测试'
          - '#    -U：每次构建检查依赖更新，可避免缓存中快照版本依赖不更新问题，但会牺牲部分性能'
          - '#    -e -X ：打印调试信息，定位疑难构建问题时建议使用此参数构建'
          - '#    -B：以batch模式运行，可避免日志打印时出现ArrayIndexOutOfBoundsException异常'
          - '# 使用场景：打包项目且不需要执行单元测试时使用'
          - mvn clean package -Dmaven.test.skip=true -U -e -X -B
          - ''
          - '# 功能：自定义settings配置'
          - '# 使用场景：如需手工指定settings.xml，可使用如下方式'
          - '# 注意事项：如无需自定义settings配置且需要私有依赖仓库，可在该任务配置《私有仓库》处添加私有依赖'
          - '# mvn -U clean package -s ./settings.xml'
          - ''
        artifacts:
          - name: docker_swarm_demo
            path:
              - ./docker-swarm-demo/target/*.jar
              - ./docker-swarm-demo/target/*.properties
          - name: security_order
            path:
              - ./security-order/target/*.jar
              - ./security-order/target/*.properties
          - name: security_market
            path:
              - ./security-market/target/*.jar
              - ./security-market/target/*.properties
          - name: security_inventory
            path:
              - ./security-inventory/target/*.jar
              - ./security-inventory/target/*.properties
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
  - name: stage-docker-jingxiang-goujian
    displayName: docker镜像构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker1
        displayName: docker-swarm-demo镜像构建
        type: cert
        certificate: 30fb7aa0-4e5a-013d-a26b-2a4f25a690ec
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./docker-swarm-demo/dockerfile/Dockerfile
        context: ./docker-swarm-demo/dockerfile
        artifacts:
          - ${docker_swarm_demo}
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
      - step: build@docker
        name: build_docker2
        displayName: security-order镜像构建
        type: cert
        certificate: 30fb7aa0-4e5a-013d-a26b-2a4f25a690ec
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./security-order/dockerfile/Dockerfile
        context: ./security-order/dockerfile
        artifacts:
          - ${security-order}
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
      - step: build@docker
        name: build_docker3
        displayName: security-market镜像构建
        type: cert
        certificate: 30fb7aa0-4e5a-013d-a26b-2a4f25a690ec
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./security-market/dockerfile/Dockerfile
        context: ./security-market/dockerfile
        artifacts:
          - ${security-market}
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
      - step: build@docker
        name: build_docker4
        displayName: security-inventory镜像构建
        type: cert
        certificate: 30fb7aa0-4e5a-013d-a26b-2a4f25a690ec
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./security-inventory/dockerfile/Dockerfile
        context: ./security-inventory/dockerfile
        artifacts:
          - ${security-inventory}
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
