spring.application.name=security-inventory
server.servlet.context-path=/inventoryApp
server.port=8083


# 数据源配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://124.222.246.77:3306/security_inventory?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123987456Mdl
#引入application-druid.properties配置文件
spring.profiles.include=druid


#redis配置
spring.redis.host=124.222.246.77
spring.redis.port=6379
spring.redis.password=123987456Mdl
spring.redis.timeout=3000


#dubbo配置
#这个名字什么用和上面的spring.application.name一样吗
dubbo.application.name=security-inventory
dubbo.scan.base-packages=com.security.inventory
dubbo.registry.address=zookeeper://124.222.246.77:2181
dubbo.registry.timeout=60000
dubbo.cloud.subscribed-services=security-order
#Dubbo协议和端口
dubbo.protocol.name=dubbo
dubbo.protocol.port=20883
dubbo.consumer.check=false
dubbo.provider.threads=800
dubbo.provider.actives=200
# 配置重试次数默认为0，防止幂等性问题，具体调用的地方也可以单独设置次数。
dubbo.consumer.retries=0
dubbo.provider.retries=0
# 配置缓存
dubbo.consumer.cache=false
dubbo.provider.cache=false


#mybatis配置
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.mapper-locations=classpath*:com/security/**/*.xml

#rocketmq配置
rocketmq.name-server=124.222.246.77:9876


#seata配置
#有时你可能需要临时禁用 Seata 而不是完全移除它,可以配置禁用
seata.enabled=false